apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-multienv
  namespace: argocd
spec:
  project: default

  source:
    repoURL: ${GIT_REPO}
    targetRevision: HEAD
    path: argocd/overlays/staging
  destination:
    server: ${SERVER}
    namespace: gitops-multienv

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
