bases:
- ../../base

patches:
- target:
    kind: Deployment
    name: website
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: 664112181258.dkr.ecr.us-east-1.amazonaws.com/multienv-vote-master:v1.0.2
